# -*- coding: utf-8 -*-
"""practice3_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGSp1NibF_O30xuDMMbJRyENHlo_kSQQ
"""

sum = 0
while True:
    a = int(input())
    sum += a
    if a == 0:
        break
print(sum)
