# -*- coding: utf-8 -*-
"""practice_3_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxh8s0w46ijqzC5xUhI7hJMQ1K2pY0yw
"""

N = int(input())
sum = 0
number = 0
for _ in range(N):
    number += 1
    sum += number
print(f"Сумма чисел от 1 до {N} = {sum}")
