# -*- coding: utf-8 -*-
"""practice_3_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxh8s0w46ijqzC5xUhI7hJMQ1K2pY0yw
"""

N = int(input())
number = 0
for _ in range(1, 11):
    number += 1
    result = N * number
    print(f"{N} x {number} = {result}")
