# -*- coding: utf-8 -*-
"""practice_3_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_tl5N5YyyZAGGNcaTLjjbHxlbkqedRt
"""

products = input().split()
for i in products:
    print(i)
