# -*- coding: utf-8 -*-
"""practice3_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhAbyl0U8XiWHirYrmFXJFpDRQ1XH0iJ
"""

age = int(input())

if age < 18:
    print("детский")
elif 18 < age < 29:
    print("молодой")
elif 30 < age < 59:
    print("взрослый")
elif 59 < age:
    print("пожилой")
