# -*- coding: utf-8 -*-
"""prakrika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZ4ke6yuOjLd15K-rXLe2Ee0Su_J079S
"""

# сперва указываем исходные данные обязательных предметов
mandatory_courses = {"Философия", "История", "Экономика"}
# затем выбранных предметов
selected_courses_1 = "ИТ-консалтинг, Экономика, Маркетинг, Философия, История, Python"
selected_courses_2 = "Философия, Физика, Python, История, Маркетинг"
selected_courses_3 = "История, Python, Кибербезопасность, Математика, Философия, Экономика, ИТ-консалтинг, Маркетинг"
# преобразуем их в списки и разделим каждый элемент запятой с пробелом, сразу преобразуем в множества
selected_courses_1 = set(selected_courses_1.split(", "))
selected_courses_2 = set(selected_courses_2.split(", "))
selected_courses_3 = set(selected_courses_3.split(", "))
# соединяем их в единое множество, в множестве априори не будет повторений
final = selected_courses_1.union(selected_courses_2, selected_courses_3)
# в конце выводим то, что входит в множество выбранных предметов, но не входит в множество обязательных предметов
print(final.difference(mandatory_courses))
